backend:
  name: github
  repo: Jacques-on-Call/StrategyContent
  branch: main
  base_url: https://auth.strategycontent.agency
  auth_endpoint: auth 

media_folder: "public/images" # Media files will be stored in public/images
public_folder: "/images" # The src attribute for uploaded media will begin with /images

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "index"
        file: "src/pages/index.astro"
        fields: &pages_fields
          - {label: "Layout", name: "layout", widget: "hidden", default: "../layouts/MainLayout.astro"}
          - {label: "Title", name: "title", widget: "string", hint: "The main H1 title of the page."}
          - {label: "Slug", name: "slug", widget: "string", hint: "The part of the URL for this page (e.g., 'about-us'). Should be unique."}
          - {label: "Description", name: "description", widget: "text", hint: "A short page summary used for search engine results."}
          - label: "Meta / SEO"
            name: "meta"
            widget: "object"
            hint: "Settings for Search Engine Optimization to improve search ranking."
            collapsed: true
            fields:
              - {label: "Meta Title", name: "title", widget: "string", required: false, hint: "A custom title for the browser tab and search results. If empty, the main Title is used."}
              - {label: "Meta Description", name: "description", widget: "text", required: false, hint: "A custom description for search results. If empty, the main Description is used."}
              - {label: "Canonical URL", name: "canonicalURL", widget: "string", required: false, hint: "The one 'true' URL for this page if it exists elsewhere, to avoid duplicate content."}
          - label: "Schema.org (JSON-LD)"
            name: "schema"
            widget: "object"
            hint: "Advanced structured data for search engines (e.g., for recipes, events). Helps with rich results."
            collapsed: true
            fields:
              - {label: "JSON-LD", name: "ldjson", widget: "code", default_language: "json", output_code_only: true, required: false}
          - label: "Page Sections"
            name: "sections"
            widget: "list"
            hint: "Build the content of the page by adding, editing, and reordering different sections."
            types:
              - label: "Hero"
                name: "hero"
                widget: "object"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
                  - {label: "Image", name: "image", widget: "image", required: false}
                  - label: "Theme"
                    name: "theme"
                    widget: "select"
                    options: ["light", "dark", "accent"]
                  - label: "Buttons"
                    name: "buttons"
                    widget: "list"
                    required: false
                    fields:
                      - {label: "Button Text", name: "text", widget: "string"}
                      - {label: "Button URL", name: "url", widget: "string"}
                      - label: "Button Style"
                        name: "style"
                        widget: "select"
                        options: ["primary", "ghost", "link"]
              - label: "Text Block"
                name: "text_block"
                widget: "object"
                fields:
                  - {label: "Content", name: "content", widget: "markdown"}
                  - label: "Theme"
                    name: "theme"
                    widget: "select"
                    options: ["light", "dark", "accent"]
              - label: "Grid"
                name: "grid"
                widget: "object"
                fields:
                  - {label: "Title", name: "title", widget: "string", required: false}
                  - label: "Theme"
                    name: "theme"
                    widget: "select"
                    options: ["light", "dark", "accent"]
                  - label: "Grid Items"
                    name: "items"
                    widget: "list"
                    fields:
                      - {label: "Title", name: "title", widget: "string"}
                      - {label: "Text", name: "text", widget: "string"}
                      - {label: "Image", name: "image", widget: "image", required: false}
              - label: "Call to Action"
                name: "cta"
                widget: "object"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Text", name: "text", widget: "string", required: false}
                  - label: "Theme"
                    name: "theme"
                    widget: "select"
                    options: ["light", "dark", "accent"]
                  - label: "Buttons"
                    name: "buttons"
                    widget: "list"
                    required: false
                    fields:
                      - {label: "Button Text", name: "text", widget: "string"}
                      - {label: "Button URL", name: "url", widget: "string"}
                      - label: "Button Style"
                        name: "style"
                        widget: "select"
                        options: ["primary", "ghost", "link"]
      - label: "About Page"
        name: "about"
        file: "src/pages/about.astro"
        fields: *pages_fields
      - label: "Contact Page"
        name: "contact"
        file: "src/pages/contact.astro"
        fields: *pages_fields
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "astro"
    format: "frontmatter"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/BlogPost.astro"}
      - {label: "Title", name: "title", widget: "string", hint: "The main headline of the blog post."}
      - {label: "Description", name: "description", widget: "text", hint: "A short summary of the post for search engines and social media previews."}
      - {label: "Author", name: "author", widget: "string", hint: "The name of the person who wrote the article."}
      - {label: "Publication Date", name: "pubDate", widget: "datetime", hint: "Set a date in the future to schedule the post."}
      - {label: "Hero Image", name: "heroImage", widget: "image", hint: "The main image that appears at the top of the post."}
      - {label: "Body", name: "body", widget: "markdown", hint: "The main content of the article, written in Markdown."}
