backend:
  name: github
  repo: Jacques-on-Call/StrategyContent
  branch: main
  base_url: https://auth.strategycontent.agency
  auth_endpoint: auth

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "discover"
    label: "Discover"
    folder: "src/pages/discover"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    summary: "{{title}}"
    extension: "astro"
    format: "frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - label: "Page Sections"
        name: "sections"
        widget: "list"
        types: &page_section_types
          - label: "Hero"
            name: "hero"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
              - {label: "Image", name: "image", widget: "image", required: false}
              - label: "Theme"
                name: "theme"
                widget: "select"
                options: ["light", "dark", "accent"]
              - label: "Buttons"
                name: "buttons"
                widget: "list"
                required: false
                fields:
                  - {label: "Button Text", name: "text", widget: "string"}
                  - {label: "Button URL", name: "url", widget: "string"}
                  - label: "Button Style"
                    name: "style"
                    widget: "select"
                    options: ["primary", "ghost", "link"]
          - label: "Text Block"
            name: "text_block"
            widget: "object"
            fields:
              - {label: "Content", name: "content", widget: "markdown"}
              - label: "Theme"
                name: "theme"
                widget: "select"
                options: ["light", "dark", "accent"]
          - label: "Grid"
            name: "grid"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string", required: false}
              - label: "Theme"
                name: "theme"
                widget: "select"
                options: ["light", "dark", "accent"]
              - label: "Grid Items"
                name: "items"
                widget: "list"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Text", name: "text", widget: "string"}
                  - {label: "Image", name: "image", widget: "image", required: false}
          - label: "Call to Action"
            name: "cta"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Text", name: "text", widget: "string", required: false}
              - label: "Theme"
                name: "theme"
                widget: "select"
                options: ["light", "dark", "accent"]
              - label: "Buttons"
                name: "buttons"
                widget: "list"
                required: false
                fields:
                  - {label: "Button Text", name: "text", widget: "string"}
                  - {label: "Button URL", name: "url", widget: "string"}
                  - label: "Button Style"
                    name: "style"
                    widget: "select"
                    options: ["primary", "ghost", "link"]
  - name: "consider"
    label: "Consider"
    folder: "src/pages/consider"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    summary: "{{title}}"
    extension: "astro"
    format: "frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - label: "Page Sections"
        name: "sections"
        widget: "list"
        types: *page_section_types
  - name: "get"
    label: "Get"
    folder: "src/pages/get"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    summary: "{{title}}"
    extension: "astro"
    format: "frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - label: "Page Sections"
        name: "sections"
        widget: "list"
        types: *page_section_types
