backend:
  name: github
  repo: Jacques-on-Call/StrategyContent
  branch: main
  base_url: https://auth.strategycontent.agency
  auth_endpoint: auth

media_folder: "public/images" # Media files will be stored in public/images
public_folder: "/images" # The src attribute for uploaded media will begin with /images

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    summary: "{{title}}"
    extension: "astro"
    format: "frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
